# Generated by Django 3.1.2 on 2020-10-15 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('p', 'Probeklausur'), ('k', 'Klausur'), ('w', 'Wiederholungsklausur')], default='k', max_length=10)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('difficulty', models.CharField(choices=[('e', 'einfach'), ('m', 'mittel'), ('s', 'schwer')], default='e', max_length=10)),
                ('year', models.IntegerField()),
                ('course', models.CharField(choices=[('EXP1', 'Experimentalphysik 1'), ('EXP2', 'Experimentalphysik 2'), ('EXP3', 'Experimentalphysik 3'), ('EXP4', 'Experimentalphysik 4')], default='EXP1', max_length=10)),
                ('subject', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=104, size=5)),
                ('exam', models.ManyToManyField(blank=True, to='FSapp.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_exercises', models.ManyToManyField(blank=True, null=True, related_name='student_failed', to='FSapp.Exercise')),
                ('solved_exercises', models.ManyToManyField(blank=True, null=True, related_name='student_solved', to='FSapp.Exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FSapp.professor'),
        ),
    ]
