# Generated by Django 3.0.7 on 2020-10-20 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('p', 'Probeklausur'), ('k', 'Klausur'), ('w', 'Wiederholungsklausur')], default='k', max_length=10)),
                ('year', models.CharField(default='20', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('preview', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('&#x2B51; &#x2606; &#x2606;', 'einfach'), ('&#x2B51; &#x2B51; &#x2606;', 'mittel'), ('&#x2B51; &#x2B51; &#x2B51;', 'schwer')], default='e', max_length=40)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('exerciseNumber', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='LatexImages/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FSapp.Course')),
                ('exam', models.ManyToManyField(blank=True, to='FSapp.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FSapp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_exercises', models.ManyToManyField(blank=True, null=True, related_name='student_failed', to='FSapp.Exercise')),
                ('favourite_exercises', models.ManyToManyField(blank=True, null=True, related_name='student_favourite', to='FSapp.Exercise')),
                ('solved_exercises', models.ManyToManyField(blank=True, null=True, related_name='student_solved', to='FSapp.Exercise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='course', chained_model_field='course', horizontal=True, to='FSapp.Subject', verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FSapp.Professor'),
        ),
    ]
