# Generated by Django 3.1.2 on 2020-11-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image1',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.FileField(blank=True, null=True, upload_to='PDFsSolution/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='question',
            field=models.FileField(blank=True, null=True, upload_to='PDFsQuestion/'),
        ),
    ]
