# Generated by Django 3.1.2 on 2020-10-15 19:35

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='courses',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='subject',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='course', chained_model_field='course', horizontal=True, to='FSapp.Subject', verbose_name='subject'),
        ),
    ]
