# Generated by Django 3.1.2 on 2020-11-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0002_auto_20201103_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question')),
            ],
        ),
        migrations.AlterField(
            model_name='exercise',
            name='answer',
            field=models.ImageField(blank=True, null=True, upload_to='solution'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='question',
        ),
        migrations.AddField(
            model_name='exercise',
            name='question',
            field=models.ManyToManyField(to='FSapp.Image'),
        ),
    ]
