# Generated by Django 3.1.2 on 2020-10-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0002_auto_20201015_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='LatexImages/'),
        ),
    ]
