# Generated by Django 3.0.7 on 2020-10-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0002_auto_20201015_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='exerciseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
