# Generated by Django 3.0.7 on 2020-10-16 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0003_auto_20201015_2316'),
        ('FSapp', '0003_auto_20201016_0113'),
    ]

    operations = [
    ]
