# Generated by Django 3.1.2 on 2020-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0003_exercise_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='FSapp/LatexImages'),
        ),
    ]
