# Generated by Django 3.1.2 on 2020-10-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0003_auto_20201015_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favourite_exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='student_favourite', to='FSapp.Exercise'),
        ),
    ]
