# Generated by Django 3.1.2 on 2020-10-16 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0004_merge_20201016_0221'),
        ('FSapp', '0004_student_favourite_exercises'),
    ]

    operations = [
    ]
