# Generated by Django 3.1.2 on 2020-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0005_merge_20201016_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('einfach', 'einfach'), ('mittel', 'mittel'), ('schwer', 'schwer')], default='e', max_length=10),
        ),
    ]
