# Generated by Django 3.1.2 on 2020-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0005_auto_20201015_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.CharField(choices=[('EXP1', 'Experimentalphysik 1'), ('EXP2', 'Experimentalphysik 2'), ('EXP3', 'Experimentalphysik 3'), ('EXP4', 'Experimentalphysik 4')], default='e', max_length=10),
        ),
    ]
