# Generated by Django 3.1.2 on 2020-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0006_auto_20201016_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('&#128161', 'einfach'), ('&#128161 &#128161', 'mittel'), ('&#128161 &#128161 &#128161', 'schwer')], default='e', max_length=40),
        ),
    ]
