# Generated by Django 3.0.7 on 2020-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0007_auto_20201016_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('&#x1F534; &#x26AA; &#x26AA;', 'einfach'), ('&#x1F534; &#x1F534; &#x26AA;', 'mittel'), ('&#x1F534; &#x1F534; &#x1F534;', 'schwer')], default='e', max_length=40),
        ),
    ]
