# Generated by Django 3.0.7 on 2020-10-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0008_auto_20201016_1246'),
        ('FSapp', '0008_auto_20201016_1929'),
    ]

    operations = [
    ]
