# Generated by Django 3.1.2 on 2020-10-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSapp', '0009_merge_20201016_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='preview',
            field=models.TextField(),
        ),
    ]
